repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: pretty-format-json
        args: ['--autofix']

  - repo: local
    hooks:
      - id: renovate-config-validator
        name: Renovate config validator
        entry: renovate/renovate renovate-config-validator
        language: docker_image
        files: ^configs/.*\.(json|json5)$
        types: [json]
